services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
  directus:
    image: directus/directus
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    depends_on:
      - database
    env_file:
      - .env
volumes:
  data:
